apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleApp
  namespace: devops  # optional
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleApp
  template:
    metadata:
      labels:
        app: sampleApp
    spec:
      containers:
      - name: sampleApp
        image: dockeritc778/sampleApp:v10.5
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: sampleApp-svc
spec:
  type: LoadBalancer
  selector:
    app: sampleApp
  ports:
    - port: 80      
      targetPort: 5000